export const tips = [
  "Enter (Start), Ctrl + Enter (Reset)",
  "Type 'terminal' to open the NerdType terminal",
  "There is no God Mode",
  "Use TAB key to auto-complete commands and filenames",
  "You can modify the game difficulty in the terminal",
  "Use number keys 1-5 to quickly navigate between pages",
  "Open terminal and type 'help' for available commands",
  "Use quick commands to modify game difficulty on-the-fly",
  "Focus on accuracy over speed - it builds your score faster",
  "Check the next word preview to prepare your fingers",
  "Try different languages to improve your vocabulary",
  "Nightmare mode can boost your overall typing speed",
  "Command mode pauses the timer - use /status to check settings",
  "Use /setbonus to adjust energy gain per word",
  "Some secrets are hidden in plain text",
  "The terminal contains hidden features",
  "Custom Mode creates your perfect typing challenge",
  "Keep fingers on home row (ASDF JKL;) for optimal typing",
  "Daily practice greatly improves typing speed",
  "Energy only depletes after your first keystroke",
];
