export const tips = [
  "Press Enter to start, Ctrl + Enter to reset game",
  "Use number keys 1-6 to quickly navigate between pages",
  "Use quick commands to modify game difficulty on-the-fly",
  "Focus on accuracy over speed - it builds your score faster",
  "Check the next word preview to prepare your fingers",
  "Try different languages to improve your vocabulary",
  "Command mode pauses the timer - use /status to check settings",
  "Use /setbonus to adjust energy gain per word",
  "Custom Mode creates your perfect typing challenge",
  "Keep fingers on home row (ASDF JKL;) for optimal typing",
  "Energy only depletes after your first keystroke",
  "Switch to Zen Mode from the settings panel",
  "Access game modes and sound options via the Settings button",
  "Tinker with game settings to unlock achievements more easily",
  "Press Enter during game for a quick restart",
  "Press Ctrl + O to toggle the settings panel",
  "Press Ctrl + I to toggle the local scoreboard",
  "Press Ctrl + U to quickly hide or show the UI buttons",
  "Press Ctrl + Z to toggle minimal UI mode",
];
